apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-config
  namespace: monitoring
data:
  loki-config.yml: |
    auth_enabled: false

    server:
      http_listen_port: 3100
      grpc_listen_port: 9095

    common:
      path_prefix: /var/loki
      storage:
        azure:
          account_name: ${AZURE_STORAGE_ACCOUNT_NAME}
          account_key: ${AZURE_STORAGE_ACCOUNT_KEY}    # Better to inject via env or secret
          container_name: ${AZURE_BLOB_CONTAINER}
      replication_factor: 3
      ring:
        instance_addr: ${POD_IP}  # use downward API in k8s manifest
        kvstore:
          store: kubernetes     # uses Kubernetes API for ring coordination
          
    ingester:
      chunk_idle_period: 5s
      max_chunk_age: 1h
      chunk_target_size: 131072

    schema_config:
      configs:
        - from: 2020-10-24
          store: boltdb-shipper
          object_store: azure
          schema: v11
          index:
            prefix: index_
            period: 24h
