apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-config
  namespace: monitoring
data:
  loki-config.yml: |
    auth_enabled: false

    server:
      http_listen_port: 3100
      grpc_listen_port: 9095

    common:
      path_prefix: /var/loki
      storage:
        azure:
          account_name: "STORAGE_NAME"
          account_key: "KEY"
          container_name: "loki-storage"
      replication_factor: 1
      ring:
        kvstore:
          store: inmemory
      
    ingester:
      chunk_idle_period: 5s
      max_chunk_age: 1h
      chunk_target_size: 131072

    schema_config:
      configs:
        - from: 2020-10-24
          store: boltdb-shipper
          object_store: azure
          schema: v11
          index:
            prefix: index_
            period: 24h
