apiVersion: v1
kind: Secret
metadata:
  name: azure-storage-secret
  namespace: monitoring
type: Opaque
data:
  AZURE_STORAGE_ACCOUNT_NAME: "STORAGE_NAME"
  AZURE_STORAGE_ACCOUNT_KEY: "KEY"
  AZURE_BLOB_CONTAINER: "loki-storage"
