apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: promtail-python-pvc
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 4Gi
  storageClassName: azurefile-csi
