version: '3.7'

services:
  python-app:
    build:
      context: C:/Users/raman/PycharmProjects/azure-mlops/kubernetes
      dockerfile: Docker_images/monitoring/Dockerfile
    container_name: python-app
    volumes:
      - ./var/log:/var/log
    ports:
      - "8000:8000"
    env_file:
      - C:/Users/raman/PycharmProjects/azure-mlops/env/.env
    restart: unless-stopped

  grafana:
    image: grafana/grafana:10.0.3
    container_name: grafana
    ports:
      - '3000:3000'
    volumes:
      - grafana-storage:/var/lib/grafana
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
          - '9090:9090'
    volumes:
          - ./prometheus.yml:/etc/prometheus/prometheus.yml
    restart: unless-stopped

  node-exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node-exporter
    ports:
      - "9100:9100"
    restart: unless-stopped

  loki:
    image: grafana/loki:2.9.2
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./loki-data:/var/loki
      - ./loki-config.yaml:/etc/loki/local-config.yaml

  promtail:
    image: grafana/promtail:2.9.2
    ports:
      - "9080:9080"
    volumes:
        - ./promtail-config.yaml:/etc/promtail/promtail.yaml
        - ./var/log:/var/log
    command: -config.file=/etc/promtail/promtail.yaml

volumes:
  grafana-storage:
