apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      labels:
        app: loki
    spec:
      containers:
        - name: loki
          image: grafana/loki:2.9.2
          ports:
            - containerPort: 3100
          volumeMounts:
            - name: loki-storage
              mountPath: /var/loki
      volumes:
        - name: loki-storage
          persistentVolumeClaim:
            claimName: loki-pvc
